[workspace]
members = [
    "chapter2",
    "chapter3/arithmetic-operations-quiz",
    "chapter5/chapter5-2",
    "chapter5/chapter5-3",
    "chapter5/chapter5-4",
    "chapter5/chapter5-5",
    "chapter8",
    "chapter10",
]
resolver = "2"
